# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create branch vercel
        run: |
          git branch vercel-deploy -D
          git branch vercel-deploy -f
          git checkout vercel-deploy
      - name: run npm install
        run: npm install
      - name: run npm build
        run: |
          webpack --config node_modules/nullstack/webpack.config.js --mode=production
          rm -rf ./node_modules
      - name: run git commit
        run: |
          git add * -f
          git config --global user.name "Nullstack Deployer"
          git config --global user.email "nullstack@deployer.ci"
          git commit -m "update vercel"
      - name: run git push
        run: git push -u origin vercel-deploy
